# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
 build:
   docker:
     - image: circleci/php:7.1-browsers
   steps:
     - checkout
     # UI に保管されている ID・パスワードを使い
     # プライベート Docker イメージによる専用 DB を稼働させる
     - setup_remote_docker:
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker container run -d --name circleci-test beaverjr/circleci-docker-test:latest
 deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker login -u $DOCKER_USER -p $DOCKER_PASS"
            ssh $SSH_USER@$SSH_HOST "docker container run -d --name circleci-test beaverjr/circleci-docker-test:latest"
workflows:
  version: 2
  build_deploy: # workflow名
    jobs:
      - build
      - deploy: 
          requires: # buildとtestが成功したら
            - build
          filters: 
            branches: # masterブランチのみ実行する
              only: 
                - master
