# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "99:bb:bc:a8:6e:6c:bb:f2:5d:c3:f8:50:71:9f:6a:0e"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/home/ec2-user/circleci/
            fi
