# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
 build:
   docker:
     - image: circleci/php:7.1-browsers
   steps:
     - checkout
     # UI に保管されている ID・パスワードを使い
     # プライベート Docker イメージによる専用 DB を稼働させる
     - setup_remote_docker:
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker run -d --name circleci-test beaverjr/circleci-docker-test:latest
 deploy:
     - image: circleci/php:7.1-browsers
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker run -d --name circleci-test beaverjr/circleci-docker-test:latest
