# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
 build:
   docker:
     - image: circleci/golang:1.8
   steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Make the executable
          command: |
            go build -o demo-app src/main.go
      - run:
          name: Build image
          command: |
            docker build -t 433649235084.dkr.ecr.ap-northeast-1.amazonaws.com/mysql:latest ./mysql
            docker build -t 433649235084.dkr.ecr.ap-northeast-1.amazonaws.com/wp:latest ./wp
      - run:
          name: Test image
          command: |
            docker run -d -p 8000:80 --name wp-test 433649235084.dkr.ecr.ap-northeast-1.amazonaws.com/wp:latest
            docker run -d --name mysql-test 433649235084.dkr.ecr.ap-northeast-1.amazonaws.com/mysql:latest
          





#workflows:
#  version: 2
#  build_deploy: # workflow名
#    jobs:
#      - build
#      - deploy: 
#          requires: # buildとtestが成功したら
#            - build
#          filters: 
#            branches: # masterブランチのみ実行する
#              only: 
#                - master
